spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/schema?characterEncoding=UTF-8&serverTimezone=UTC}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}

  jpa:
    database: mysql

    hibernate:
      ddl-auto: validate

  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST}

jwt:
  secret: ${SECRET_KEY:scretgdkdfkldjkaljldnlkandlkfnalsdkjflkasnflksndflkjsadlkfnscretgdkdfkldjkaljldnlkandlkfnalsdkjflkasnflksndflkjsadlkfnscretgdkdfkldjkaljldnlkandlkfnalsdkjflkasnflksndflkjsadlkfn}
  accessExp: ${JWT_ACCESS_EXP:3600}
  refreshExp: ${JWT_REFRESH_EXP:3600000}
  header: ${JWT_HEADER:Authorization}
  prefix: ${JWT_PREFIX:Bearer}

mail:
  host: smtp.gmail.com
  port: ${MAIL_PORT:587}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  auth: true
  enable: true
  required: true