name: "Todo"
description: "어떤 이슈를 만드시나요? 📗"
body:
  - type: textarea
    attributes:
      label: Describe
      description: |
        [개요] 할일에 관한 설명을 간단하게 작성해주세요.
      placeholder: |
        DropDownMenu 제작

  - type: textarea
    attributes:
      label: Work
      description: |
        [작업내용] 무슨 작업을 하셨나요?
      placeholder: |
        - [ ] 기능 A 개발 완료
        - [ ] API 연동 테스트 진행

  - type: textarea
    attributes:
      label: Additional
      description: |
        [추가사항] 추가로 할말이 있으신가요?
